name: Sync

on:
  workflow_dispatch:
    inputs:
      build_env:
        required: false
        type: string

env:
  AWS_REGION: ap-southeast-1

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: SVN checkout 1
        uses: Meland-Inc/svn-checkout@main
        with:
          resources_url: "http://18.141.188.61/svn/meland_bellplanet/versionRes/trunk/settings/resource/item_icon/cloth_ic/"
          target_dir: ./github/workspace/data
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: SVN checkout 2
        uses: Meland-Inc/svn-checkout@main
        with:
          resources_url: "http://18.141.188.61/svn/meland_bellplanet/versionRes/trunk/settings/resource/item_icon/ic_ic/"
          target_dir: ./github/workspace/data
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: SVN checkout 3
        uses: Meland-Inc/svn-checkout@main
        with:
          resources_url: "http://18.141.188.61/svn/meland_bellplanet/versionRes/trunk/settings/resource/item_icon/icob_ic/"
          target_dir: ./github/workspace/data
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: SVN checkout 4
        uses: Meland-Inc/svn-checkout@main
        with:
          resources_url: "http://18.141.188.61/svn/meland_bellplanet/versionRes/trunk/settings/resource/item_icon/monster_ic/"
          target_dir: ./github/workspace/data
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: SVN checkout 5
        uses: Meland-Inc/svn-checkout@main
        with:
          resources_url: "http://18.141.188.61/svn/meland_bellplanet/versionRes/trunk/settings/resource/item_icon/npcbyuser_ic/"
          target_dir: ./github/workspace/data
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: SVN checkout 6
        uses: Meland-Inc/svn-checkout@main
        with:
          resources_url: "http://18.141.188.61/svn/meland_bellplanet/versionRes/trunk/settings/resource/item_icon/weapon_ic/"
          target_dir: ./github/workspace/data
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: SVN checkout quiz
        uses: Meland-Inc/svn-checkout@main
        with:
          resources_url: "http://18.141.188.61/svn/meland_bellplanet/quiz"
          target_dir: ./github/workspace/data/quiz
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Commit icon's
        uses: EndBug/add-and-commit@v8
        with:
          new_branch: gh-pages
          push: true
          add: ./data
          author_name: AlbertHuang
          author_email: r.albert.huang@gmail.com
          message: Sync icon's from svn
